# Generated by Django 3.2.10 on 2021-12-28 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日'),
            preserve_default=False,
        ),
    ]
